import {
  LandRecord,
  ExtractedLandField,
  TrackingApplication,
  VerificationCheckResult,
  FAQItem,
  DocumentItem,
} from "./types";

// ============================================================================
// 1. CENTRALIZED MOCK LAND RECORDS (Official Digital Title Registry)
// ============================================================================
export const MOCK_LAND_RECORDS: LandRecord[] = [
  {
    id: "1",
    ror_number: "ROR-KA-2026-98124",
    survey_number: "142/3A",
    hissa_number: "Hissa 1",
    property_id: "PID-KA-RAM-8901",
    owner_name: "B. R. Shivashankaraiah",
    kannada_owner_name: "ಬಿ. ಆರ್. ಶಿವಶಂಕರಯ್ಯ",
    father_or_guardian_name: "Late Ramakrishnaiah",
    state: "Karnataka",
    district: "Ramanagara",
    taluk: "Bidadi",
    hobli: "Bidadi Hobli",
    village: "Kenchanakuppe",
    kannada_village_name: "ಕೆಂಚನಕುಪ್ಪೆ",
    land_extent_acres: 2,
    land_extent_guntas: 14,
    total_area_text: "2 Acres 14 Guntas (9,510 sq. meters)",
    land_classification: "Dry Agricultural (Khushki)",
    soil_type: "Red Loamy Soil (Category A)",
    revenue_assessment_inr: 24.50,
    registration_date: "1994-08-14",
    issuing_authority: "Tahsildar Office, Ramanagara Kasaba",
    status: "Digitally Verified",
    verification_seal_number: "SEAL-KA-REV-4091-B",
    sha256_hash: "7f6d3b68d46b6d9cbbca99141c127d1e4cc9c542c66eec4a214b77b682b4ec88",
    document_type: "Record of Rights (RTC / Pahani)",
    source_pdf_filename: "KA_Bidadi_Sy142_3A_RTC.pdf",
    download_url: "#",
  },
  {
    id: "2",
    ror_number: "ROR-KA-2026-98125",
    survey_number: "142/3B",
    hissa_number: "Hissa 2",
    property_id: "PID-KA-RAM-8902",
    owner_name: "C. M. Gangadharappa & Sons",
    kannada_owner_name: "ಸಿ. ಎಂ. ಗಂಗಾಧರಪ್ಪ ಮತ್ತು ಮಕ್ಕಳು",
    father_or_guardian_name: "Mallappa Gowda",
    state: "Karnataka",
    district: "Ramanagara",
    taluk: "Bidadi",
    hobli: "Bidadi Hobli",
    village: "Kenchanakuppe",
    kannada_village_name: "ಕೆಂಚನಕುಪ್ಪೆ",
    land_extent_acres: 1,
    land_extent_guntas: 28,
    total_area_text: "1 Acre 28 Guntas (6,879 sq. meters)",
    land_classification: "Wet Agricultural (Tari)",
    soil_type: "Alluvial Clay Soil",
    revenue_assessment_inr: 32.00,
    registration_date: "2001-11-22",
    issuing_authority: "Tahsildar Office, Ramanagara Kasaba",
    status: "Digitally Verified",
    verification_seal_number: "SEAL-KA-REV-4092-A",
    sha256_hash: "3a8b9c1d2e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    document_type: "Record of Rights (RTC / Pahani)",
    source_pdf_filename: "KA_Bidadi_Sy142_3B_RTC.pdf",
    download_url: "#",
  },
  {
    id: "3",
    ror_number: "ROR-KA-2026-44012",
    survey_number: "88/1",
    hissa_number: "Hissa 1",
    property_id: "PID-KA-BLR-1004",
    owner_name: "Parvathamma w/o N. R. Narayana",
    kannada_owner_name: "ಪಾರ್ವತಮ್ಮ ಕೋಂ ಎನ್. ಆರ್. ನಾರಾಯಣ",
    father_or_guardian_name: "N. R. Narayana",
    state: "Karnataka",
    district: "Bengaluru Urban",
    taluk: "Bengaluru South",
    hobli: "Kengeri Hobli",
    village: "Kumbalgodu",
    kannada_village_name: "ಕುಂಬಳಗೋಡು",
    land_extent_acres: 0,
    land_extent_guntas: 30,
    total_area_text: "0 Acres 30 Guntas (3,035 sq. meters)",
    land_classification: "Non-Agricultural (Converted)",
    soil_type: "Commercial / Residential Converted",
    revenue_assessment_inr: 150.00,
    registration_date: "2018-04-10",
    issuing_authority: "Assistant Commissioner, Bengaluru South",
    status: "Digitally Verified",
    verification_seal_number: "SEAL-KA-BLR-7721-C",
    sha256_hash: "9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e",
    document_type: "Sale Deed (Kraya Patra)",
    source_pdf_filename: "Kumbalgodu_Deed_Sy88_1.pdf",
    download_url: "#",
  },
  {
    id: "4",
    ror_number: "ROR-KA-2026-55901",
    survey_number: "204/2",
    hissa_number: "Hissa 2",
    property_id: "PID-KA-MYS-3310",
    owner_name: "Smt. K. Ratnamma & K. Suresh",
    kannada_owner_name: "ಶ್ರೀಮತಿ ಕೆ. ರತ್ನಮ್ಮ ಮತ್ತು ಕೆ. ಸುರೇಶ್",
    father_or_guardian_name: "Late Krishnappa",
    state: "Karnataka",
    district: "Mysuru",
    taluk: "T. Narasipura",
    hobli: "Bannur Hobli",
    village: "Kodagalli",
    kannada_village_name: "ಕೊಡಗಳ್ಳಿ",
    land_extent_acres: 3,
    land_extent_guntas: 5,
    total_area_text: "3 Acres 05 Guntas (12,646 sq. meters)",
    land_classification: "Garden Land (Bagayat)",
    soil_type: "Black Cotton Soil (Arecanut Plantation)",
    revenue_assessment_inr: 68.40,
    registration_date: "2012-07-19",
    issuing_authority: "Tahsildar Office, T. Narasipura",
    status: "Digitally Verified",
    verification_seal_number: "SEAL-KA-MYS-1140-A",
    sha256_hash: "e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4",
    document_type: "Record of Rights (RTC / Pahani)",
    source_pdf_filename: "MYS_Bannur_Sy204_2.pdf",
    download_url: "#",
  },
  {
    id: "5",
    ror_number: "ROR-KA-2026-61022",
    survey_number: "76/4",
    hissa_number: "Hissa 4",
    property_id: "PID-KA-MND-4411",
    owner_name: "H. L. Chennegowda",
    kannada_owner_name: "ಹೆಚ್. ಎಲ್. ಚೆನ್ನೇಗೌಡ",
    father_or_guardian_name: "Lingegowda",
    state: "Karnataka",
    district: "Mandya",
    taluk: "Maddur",
    hobli: "Koppa Hobli",
    village: "Channasandra",
    kannada_village_name: "ಚನ್ನಸಂದ್ರ",
    land_extent_acres: 4,
    land_extent_guntas: 18,
    total_area_text: "4 Acres 18 Guntas (17,998 sq. meters)",
    land_classification: "Wet Agricultural (Tari)",
    soil_type: "Canal Irrigated Sugarcane Tract",
    revenue_assessment_inr: 85.00,
    registration_date: "1988-02-05",
    issuing_authority: "Tahsildar Office, Maddur",
    status: "Under Review",
    verification_seal_number: "SEAL-KA-MND-9902-D",
    sha256_hash: "11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff",
    document_type: "Mutation Extract",
    source_pdf_filename: "Maddur_Mutation_Sy76_4.pdf",
    download_url: "#",
  },
];

// ============================================================================
// 2. MOCK EXTRACTED FIELDS FOR REVIEW WORKFLOW
// ============================================================================
export const MOCK_EXTRACTED_LAND_FIELDS: ExtractedLandField[] = [
  {
    key: "owner_name",
    label: "Primary Land Owner (Record of Rights)",
    original_kannada: "ಶ್ರೀ ಬಿ. ಆರ್. ಶಿವಶಂಕರಯ್ಯ",
    english_normalized: "B. R. Shivashankaraiah",
    confidence: 0.98,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.24, x_max: 0.58, y_max: 0.28 },
  },
  {
    key: "father_name",
    label: "Father / Guardian Name",
    original_kannada: "ದಿವಂಗತ ರಾಮಕೃಷ್ಣಯ್ಯ",
    english_normalized: "Late Ramakrishnaiah",
    confidence: 0.96,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.30, x_max: 0.45, y_max: 0.34 },
  },
  {
    key: "survey_number",
    label: "Survey / Khasra Number",
    original_kannada: "ಸರ್ವೆ ನಂ: ೧೪೨/೩ ಎ (ಹಿಸ್ಸಾ ೧)",
    english_normalized: "142/3A (Hissa 1)",
    confidence: 0.99,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.62, y_min: 0.24, x_max: 0.88, y_max: 0.28 },
  },
  {
    key: "land_extent",
    label: "Total Land Extent / Area",
    original_kannada: "೨ ಎಕರೆ ೧೪ ಗುಂಟೆ",
    english_normalized: "2 Acres 14 Guntas",
    confidence: 0.97,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.62, y_min: 0.30, x_max: 0.85, y_max: 0.34 },
  },
  {
    key: "village_taluk",
    label: "Village & Taluk Jurisdiction",
    original_kannada: "ಕೆಂಚನಕುಪ್ಪೆ ಗ್ರಾಮ, ಬಿಡದಿ ಹೋಬಳಿ, ರಾಮನಗರ ತಾಲೂಕು",
    english_normalized: "Kenchanakuppe Village, Bidadi Hobli, Ramanagara Taluk",
    confidence: 0.98,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.38, x_max: 0.75, y_max: 0.42 },
  },
  {
    key: "registration_date",
    label: "Document Registration Date",
    original_kannada: "೧೪-೦೮-೧೯೯೪",
    english_normalized: "1994-08-14",
    confidence: 0.95,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.46, x_max: 0.35, y_max: 0.50 },
  },
  {
    key: "land_classification",
    label: "Land Classification & Soil Type",
    original_kannada: "ಖುಷ್ಕಿ (ಒಣ ಕೃಷಿ ಭೂಮಿ) - ಕೆಂಪು ಮಣ್ಣು",
    english_normalized: "Dry Agricultural (Khushki) • Red Loamy Soil",
    confidence: 0.94,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.40, y_min: 0.46, x_max: 0.88, y_max: 0.50 },
  },
  {
    key: "revenue_assessment",
    label: "Annual Land Revenue Assessment",
    original_kannada: "ಕಂದಾಯ ಆಕಾರ: ರೂ. ೨೪.೫೦",
    english_normalized: "INR 24.50 / year",
    confidence: 0.78,
    is_low_confidence: true, // low confidence warning demo
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.54, x_max: 0.42, y_max: 0.58 },
  },
  {
    key: "adjacent_boundaries",
    label: "Four Boundaries (Chaturbandi)",
    original_kannada: "ಪೂರ್ವ: ರಾಜಕಾಲುವೆ, ಪಶ್ಚಿಮ: ಬೈರೇಗೌಡರ ಜಮೀನು, ಉತ್ತರ: ಗ್ರಾಮ ರಸ್ತೆ, ದಕ್ಷಿಣ: ಸರ್ವೆ ನಂ ೧೪೨/೩ಬಿ",
    english_normalized: "East: Raja Kaluve; West: Byregowda Land; North: Village Road; South: Sy No. 142/3B",
    confidence: 0.91,
    is_low_confidence: false,
    page_number: 1,
    bounding_box: { x_min: 0.12, y_min: 0.62, x_max: 0.92, y_max: 0.70 },
  },
];

// ============================================================================
// 3. MOCK CITIZEN TRACKING APPLICATIONS
// ============================================================================
export const MOCK_TRACKING_APPLICATIONS: Record<string, TrackingApplication> = {
  "REQ-KA-2026-001": {
    request_id: "REQ-KA-2026-001",
    mobile_number: "9876543210",
    document_type: "Physical RTC / Record of Rights",
    survey_number: "142/3A",
    owner_name: "B. R. Shivashankaraiah",
    location: "Bidadi Hobli, Ramanagara",
    submission_date: "2026-03-10 10:30 AM",
    estimated_completion: "2026-03-10 11:00 AM",
    current_status: "Completed",
    progress_percentage: 100,
    record_id: "1",
    steps: [
      {
        title: "Submitted",
        description: "Document scanned and uploaded with SHA-256 hash stamp.",
        timestamp: "10:30 AM",
        status: "completed",
      },
      {
        title: "Document Reading",
        description: "Indic OCR scanned Kannada handwriting and layout coordinates.",
        timestamp: "10:33 AM",
        status: "completed",
      },
      {
        title: "Information Review",
        description: "Revenue Inspector validated survey bounds and mathematical balance.",
        timestamp: "10:45 AM",
        status: "completed",
      },
      {
        title: "Verification",
        description: "Cross-verified with sub-registrar database and certified.",
        timestamp: "10:55 AM",
        status: "completed",
      },
      {
        title: "Completed",
        description: "Official Digital Title Record issued with digital seal.",
        timestamp: "11:00 AM",
        status: "completed",
      },
    ],
  },
  "REQ-KA-2026-002": {
    request_id: "REQ-KA-2026-002",
    mobile_number: "9988776655",
    document_type: "Sale Deed (Kraya Patra)",
    survey_number: "88/1",
    owner_name: "Parvathamma w/o N. R. Narayana",
    location: "Kengeri Hobli, Bengaluru South",
    submission_date: "2026-03-11 02:15 PM",
    estimated_completion: "2026-03-11 04:00 PM",
    current_status: "Information Review",
    progress_percentage: 60,
    record_id: "3",
    steps: [
      {
        title: "Submitted",
        description: "Application received and cataloged.",
        timestamp: "02:15 PM",
        status: "completed",
      },
      {
        title: "Document Reading",
        description: "Spatial OCR extracted 24 entity fields.",
        timestamp: "02:22 PM",
        status: "completed",
      },
      {
        title: "Information Review",
        description: "Under review by Assistant Revenue Officer.",
        timestamp: "02:40 PM",
        status: "current",
      },
      {
        title: "Verification",
        description: "Pending statutory boundary validation.",
        timestamp: "Expected 03:30 PM",
        status: "upcoming",
      },
      {
        title: "Completed",
        description: "Digital certificate generation.",
        timestamp: "Expected 04:00 PM",
        status: "upcoming",
      },
    ],
  },
  "1": {
    request_id: "REQ-KA-2026-001",
    mobile_number: "9876543210",
    document_type: "Physical RTC / Record of Rights",
    survey_number: "142/3A",
    owner_name: "B. R. Shivashankaraiah",
    location: "Bidadi Hobli, Ramanagara",
    submission_date: "2026-03-10 10:30 AM",
    estimated_completion: "2026-03-10 11:00 AM",
    current_status: "Completed",
    progress_percentage: 100,
    record_id: "1",
    steps: [
      {
        title: "Submitted",
        description: "Document scanned and uploaded with SHA-256 hash stamp.",
        timestamp: "10:30 AM",
        status: "completed",
      },
      {
        title: "Document Reading",
        description: "Indic OCR scanned Kannada handwriting and layout coordinates.",
        timestamp: "10:33 AM",
        status: "completed",
      },
      {
        title: "Information Review",
        description: "Revenue Inspector validated survey bounds and mathematical balance.",
        timestamp: "10:45 AM",
        status: "completed",
      },
      {
        title: "Verification",
        description: "Cross-verified with sub-registrar database and certified.",
        timestamp: "10:55 AM",
        status: "completed",
      },
      {
        title: "Completed",
        description: "Official Digital Title Record issued with digital seal.",
        timestamp: "11:00 AM",
        status: "completed",
      },
    ],
  },
};

// ============================================================================
// 4. MOCK RECORD VERIFICATION LOOKUPS
// ============================================================================
export const MOCK_VERIFICATION_LOOKUP: Record<string, VerificationCheckResult> = {
  "ROR-KA-2026-98124": {
    is_verified: true,
    record_id: "1",
    ror_number: "ROR-KA-2026-98124",
    survey_number: "142/3A",
    owner_name: "B. R. Shivashankaraiah",
    issuing_authority: "Tahsildar Office, Ramanagara Kasaba",
    verification_timestamp: "2026-03-10T11:00:00Z",
    sha256_hash: "7f6d3b68d46b6d9cbbca99141c127d1e4cc9c542c66eec4a214b77b682b4ec88",
    digital_seal: "NIC-DIGILOCKER-CERT-2026-OK",
    details: MOCK_LAND_RECORDS[0],
  },
  "1": {
    is_verified: true,
    record_id: "1",
    ror_number: "ROR-KA-2026-98124",
    survey_number: "142/3A",
    owner_name: "B. R. Shivashankaraiah",
    issuing_authority: "Tahsildar Office, Ramanagara Kasaba",
    verification_timestamp: "2026-03-10T11:00:00Z",
    sha256_hash: "7f6d3b68d46b6d9cbbca99141c127d1e4cc9c542c66eec4a214b77b682b4ec88",
    digital_seal: "NIC-DIGILOCKER-CERT-2026-OK",
    details: MOCK_LAND_RECORDS[0],
  },
  "ROR-KA-2026-44012": {
    is_verified: true,
    record_id: "3",
    ror_number: "ROR-KA-2026-44012",
    survey_number: "88/1",
    owner_name: "Parvathamma w/o N. R. Narayana",
    issuing_authority: "Assistant Commissioner, Bengaluru South",
    verification_timestamp: "2026-03-11T09:30:00Z",
    sha256_hash: "9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e",
    digital_seal: "NIC-DIGILOCKER-CERT-2026-OK",
    details: MOCK_LAND_RECORDS[2],
  },
};

// ============================================================================
// 5. MOCK CITIZEN SUPPORT & KNOWLEDGE BASE FAQS
// ============================================================================
export const MOCK_FAQS: FAQItem[] = [
  {
    id: "faq-1",
    category: "General",
    question: "What is BhumiAI and how does it help citizens?",
    answer:
      "BhumiAI is a National Digital Land Mission portal designed to digitize historical physical land deeds, Record of Rights (RTC/Pahani), and mutation extracts. Using spatial Indic AI, it converts scanned paper records into legally admissible, searchable digital titles with cryptographic proof.",
  },
  {
    id: "faq-2",
    category: "Digitization",
    question: "Which document formats and languages are supported for digitization?",
    answer:
      "You can upload PDF documents or high-resolution images (JPG, PNG, TIFF) up to 50MB. BhumiAI supports multilingual Indic OCR including Kannada (both modern printed script and traditional Modi/handwritten deed scripts) and English.",
  },
  {
    id: "faq-3",
    category: "Search",
    question: "How do I search for a land parcel without knowing the exact survey number?",
    answer:
      "You can search by Primary Land Owner Name or Property Identification Number (PID). Select your State, District, and Taluk, then choose the 'Search by Owner Name' tab to view matching cadastral records in that jurisdiction.",
  },
  {
    id: "faq-4",
    category: "Verification",
    question: "Is a BhumiAI digital record legally admissible for property transactions and bank loans?",
    answer:
      "Yes. Every digitized title processed through BhumiAI undergoes statutory verification, is stamped with an immutable SHA-256 digital signature, and is integrated with DigiLocker under Section 65B of the Indian Evidence Act.",
  },
  {
    id: "faq-5",
    category: "Digitization",
    question: "What should I do if an extracted field contains an OCR spelling error?",
    answer:
      "On the 'Review Extracted Information' screen, all fields are editable. You can correct names or numbers directly. Once you check the confirmation box and click 'Confirm & Submit', your correction is saved and fed to our active-learning ground truth pipeline.",
  },
  {
    id: "faq-6",
    category: "Legal",
    question: "How are boundary disputes and joint ownership shares (Hissa) handled?",
    answer:
      "BhumiAI extracts individual hissa numbers, four-boundary (Chaturbandi) descriptions, and total extent in Acres/Guntas. If boundary discrepancies exist, the record is flagged as 'Under Review' for Revenue Inspector field verification.",
  },
];
